export const topicLabels: Record<string, string> = {
    // PHP
    'php.basic_syntax': 'Базовый синтаксис',
    'php.operators': 'Операторы и приведение',
    'php.arrays': 'Массивы',
    'php.strings': 'Строки',
    'php.regex': 'Регулярные выражения',
    'php.oop': 'ООП',
    'php.magic_methods': 'Магические методы',
    'php.closures': 'Замыкания',
    'php.generators': 'Генераторы',
    'php.exceptions': 'Исключения',
    'php.types': 'Типы',
    'php.php8_features': 'PHP 8 фичи',
    'php.composer_autoload': 'Composer и автозагрузка',
    'php.std_lib': 'Стандартная библиотека (SPL)',
    'php.runtime': 'Runtime: GC, OPcache, JIT',
    'php.files_streams': 'Файлы и потоки',
    'php.sessions': 'Сессии',
    'php.security': 'Безопасность',
    'php.psr': 'PSR-стандарты',
    'php.algorithms': 'Алгоритмы',
    'php.symfony': 'Symfony-компоненты',
    'php.testing': 'Тестирование',
    'php.code_traps': 'Live-coding ловушки',
    'php.basic_qa': 'Краткие Q/A',
    'php.cloze': 'Cloze',
    'php.type_in': 'Type-in',
    'php.assemble': 'Сборка',

    // OOP
    'oop.basic_concepts': 'Базовые понятия',
    'oop.four_principles': '4 принципа ООП',
    'oop.visibility': 'Видимость',
    'oop.constructor_destructor': 'Конструктор и деструктор',
    'oop.static_members': 'Статические члены',
    'oop.abstract_interfaces': 'Абстрактные классы и интерфейсы',
    'oop.traits': 'Трейты',
    'oop.composition_vs_inheritance': 'Композиция vs наследование',
    'oop.solid': 'SOLID',
    'oop.gof_creational': 'GoF: порождающие',
    'oop.gof_structural': 'GoF: структурные',
    'oop.gof_behavioral': 'GoF: поведенческие',
    'oop.dependency_injection': 'DI, IoC, Service Locator',
    'oop.ddd': 'DDD',
    'oop.event_sourcing_cqrs': 'Event Sourcing, CQRS',
    'oop.anemic_vs_rich': 'Anemic vs Rich Domain',
    'oop.coupling_cohesion': 'Coupling/Cohesion',
    'oop.clean_code': 'Чистый код',
    'oop.misc': 'Дополнительные',
    'oop.basic_qa': 'Краткие Q/A',
    'oop.cloze': 'Cloze',
    'oop.assemble': 'Сборка',

    // Laravel
    'laravel.routing': 'Маршрутизация',
    'laravel.controllers': 'Контроллеры',
    'laravel.middleware': 'Middleware',
    'laravel.requests_validation': 'Request и валидация',
    'laravel.eloquent_basics': 'Eloquent: основы',
    'laravel.eloquent_relations': 'Eloquent: связи',
    'laravel.eloquent_advanced': 'Eloquent: продвинутое',
    'laravel.migrations_seeders': 'Миграции и сидеры',
    'laravel.service_container': 'Service Container',
    'laravel.service_providers': 'Service Providers',
    'laravel.queues_jobs': 'Очереди и Jobs',
    'laravel.events_listeners': 'События и листенеры',
    'laravel.cache_session': 'Cache и сессии',
    'laravel.auth_authorization': 'Auth и авторизация',
    'laravel.artisan': 'Artisan',
    'laravel.testing': 'Тестирование',
    'laravel.api_resources': 'API Resources',
    'laravel.mail_notifications': 'Mail и уведомления',
    'laravel.storage_files': 'Storage и файлы',
    'laravel.inertia_frontend': 'Inertia и фронтенд',
    'laravel.octane_horizon': 'Octane и Horizon',
    'laravel.collections': 'Коллекции',
    'laravel.legacy_migration': 'Legacy и миграция Yii2 → Laravel',
    'laravel.debug_scenarios': 'Debug-сценарии (find the bug)',
    'laravel.misc': 'Дополнительные',
    'laravel.basic_qa': 'Краткие Q/A',
    'laravel.cloze': 'Cloze',
    'laravel.type_in': 'Type-in',
    'laravel.assemble': 'Сборка',

    // Yii2
    'yii2.basics': 'Основы и приложение',
    'yii2.components': 'Компоненты',
    'yii2.events': 'События',
    'yii2.behaviors': 'Поведения',
    'yii2.di': 'DI и Service Locator',
    'yii2.controllers': 'Контроллеры',
    'yii2.routing': 'Маршрутизация (UrlManager)',
    'yii2.requests': 'Request и Response',
    'yii2.validators': 'Валидаторы',
    'yii2.active_form': 'ActiveForm и Html',
    'yii2.views': 'Views и Widgets',
    'yii2.asset_bundles': 'AssetBundles',
    'yii2.modules': 'Модули',
    'yii2.active_record': 'ActiveRecord',
    'yii2.relations': 'Связи AR',
    'yii2.query_builder': 'Query Builder и DAO',
    'yii2.migrations': 'Миграции',
    'yii2.data_provider': 'DataProvider, GridView',
    'yii2.authentication': 'Аутентификация',
    'yii2.authorization': 'Авторизация и RBAC',
    'yii2.filters': 'Фильтры',
    'yii2.rest': 'REST API',
    'yii2.security': 'Безопасность',
    'yii2.cache': 'Кэширование',
    'yii2.logging': 'Логирование',
    'yii2.errors': 'Ошибки и исключения',
    'yii2.i18n': 'i18n и Formatter',
    'yii2.mail': 'Mailer',
    'yii2.console': 'Консольные команды',
    'yii2.gii': 'Gii',
    'yii2.testing': 'Тестирование (Codeception)',
    'yii2.misc': 'Дополнительные',

    // Database — Работа с данными и хранилищами
    //   Базовый SQL
    'database.basic_concepts': 'Базовые понятия',
    'database.sql_basics': 'SQL базовый',
    'database.normalization': 'Нормализация',
    'database.indexes': 'Индексы',
    'database.transactions_acid': 'Транзакции и ACID',
    'database.optimization': 'Оптимизация запросов',
    'database.mysql': 'MySQL',
    'database.postgresql': 'PostgreSQL',
    'database.infrastructure_backup': 'Pooling, WAL, бэкапы',
    //   Распределённые БД и хранилища
    'database.partitioning': 'Партиционирование',
    'database.distributed': 'Репликация и шардирование',
    'database.nosql': 'NoSQL',
    'database.elasticsearch': 'Elasticsearch',
    //   Прочее (режимы)
    'database.basic_qa': 'Краткие Q/A',
    'database.cloze': 'Cloze',
    'database.type_in': 'Type-in',
    'database.assemble': 'Сборка',

    // System Design
    'system_design.architecture': 'Архитектура',
    'system_design.caching': 'Кэширование',
    'system_design.messaging_queues': 'Очереди и сообщения',
    'system_design.distributed': 'Распределённые системы',
    'system_design.api': 'API',
    'system_design.security': 'Безопасность',
    'system_design.performance': 'Производительность',
    'system_design.design_tasks': 'System Design задачи',

    // DevOps
    'devops.basics': 'DevOps',
    'devops.git': 'Git',
    'devops.tools': 'Shell-инструменты',

    // Networking
    'networking.basics': 'Основы сетей',
    'networking.transport': 'TCP/UDP',
    'networking.tls': 'TLS/HTTPS',
    'networking.http': 'HTTP',
    'networking.dns': 'DNS',
    'networking.loadbalancers': 'Балансировщики',
    'networking.realtime': 'Realtime (WebSocket, SSE)',

    // Security
    'security.owasp': 'OWASP Top 10',
    'security.auth': 'Аутентификация и авторизация',
    'security.sessions': 'Сессии и cookies',
    'security.crypto': 'Криптография',
    'security.tokens': 'Токены (JWT, OAuth)',
    'security.secrets': 'Секреты и конфигурация',
    'security.web_attacks': 'Веб-атаки (XSS, CSRF, SQLi)',

    // Testing
    'testing.basics': 'Основы тестирования',
    'testing.doubles': 'Test doubles (mock/stub)',
    'testing.practice': 'Практики тестирования',
    'testing.tools': 'Инструменты (PHPUnit, Pest)',
};

export function topicLabel(slug: string | null | undefined): string | null {
    if (!slug) {
        return null;
    }

    return topicLabels[slug] ?? slug;
}
